import Head from "next/head";
import { useState } from "react";
import GameUI from "../components/GameUI";
import useSound from "use-sound";
import { useEffect } from "react";
import Image from "next/image";
import MilyonerLogo from "/public/Milyoner-Logo.png";
import { motion } from "framer-motion";

export default function Home() {
  const [home, setHome] = useState(true);
  const [name, setName] = useState("");
  const [play] = useSound("/sounds/play.mp3");

  useEffect(() => {play()}, [play]);

  return (
    <div className="x min-h-screen mx-auto flex flex-col items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-5xl grid grid-cols-6 text-white mx-auto min-h-[80vh]">
        {home ? (
          <motion.div
            initial={{ y: -500 }}
            animate={{ y: 0 }}
            className="flex flex-col items-center col-span-6 space-y-6 "
          >
            <Image alt="logo" height={200} width={200} src={MilyonerLogo} />
            <h1 className="text-4xl">HOŞGELDİNİZ</h1>
            <input
              placeholder="Adınızı Girin"
              className="text-black h-10 text-2xl outline-none "
              value={name}
              onChange={(e) => setName(e.target.value)}
              type="text"
            />
            <motion.button
              whileHover={{ scale: 1.1 }}
              animate={{ rotateZ: 360 }}
              className="border-2 font-semibold text-2xl border-[#805AB9] bg-black px-10 py-4 hover:bg-green-600 transition-all duration-200"
              onClick={() => setHome(false)}
            >
              OYUNA BAŞLA
            </motion.button>
          </motion.div>
        ) : (
          <GameUI setHome={setHome} name={name} />
        )}
      </div>
    </div>
  );
}
